# Generated by Django 6.0.6 on 2026-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0003_borrowing_borrow_days_reservation_borrow_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='is_fine_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='borrowing',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
